/*
      Author: Junyuan Zeng
      Modified by Yufei Gu
*/

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

void usage(int argc, char *argv[])
{
   if (argc < 2)
    {
        fprintf(stderr, "%s [File (Generated By 'objdump -dl obj1')] \n", argv[0]);
        exit(1);
    }
}

int main(int argc, char *argv[])
{
    usage(argc, argv);
    char* filename = argv[1];
    FILE* fp=fopen(filename, "r");
    char buf1[1024];
    char buf2[1024];
    char fun[1024];
    int end=0;
    int line;
    int start=0;
    if(fp!=NULL)
    {
        fgets(buf1, 1024, fp);
        while(!end)
        {
            if(buf1[0]=='\n')
            {
                fgets(buf1, 1024, fp);
                char *s=strstr(buf1, "<");
                if(s == NULL)
                    continue;
                strcpy(fun,s+1);
                fun[strlen(fun)-3]='\0';
                printf("0\tNew_Function_Start\t0\tEmpty\n");
                start=1;
            }
            while(!end)
            {
                if(fgets(buf1, 1024, fp)==NULL)
                {
                    end=1;
                }
                if(buf1[0]=='\n')
                {
                    break;

                }else if(buf1[0]=='/')
                {
                    char *s=strstr(buf1,":");
                    sscanf(s+1, "%d", &line);
                    *s='\0';
                    strcpy(buf2, buf1);
                }
                else if(buf1[strlen(buf1)-2]==':')
                {
                    strcpy(fun, buf1);
                    fun[strlen(fun)-2]='\0';
                    if(!start)
                        printf("0\tNew_Function_Start\t0\tEmpty\n");
                    start=0;
                }
                else
                {
                    buf1[8]='\0';
                    printf("%s\t%s\t%d\t%s\n", buf1, fun, line, buf2);
                }

            }
        }
        fclose(fp);
    }
   
    return 1;
}
